FROM node:lts-alpine

WORKDIR /app

RUN npm install -g pnpm
RUN pnpm config set dangerouslyAllowAllBuilds true

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3002

CMD ["pnpm", "run", "start:dev"]
